### ISSUE TITLE
Does it truly support Linux or macOS ? 

### ISSUE THREAD

**Issue by cpuu** [virtualrealitysystems/aumfor#1]
Does it truly support Linux or macOS ? 

It seems to support only windows platform.

is there any additional way(that I didn't catch) to suit linux system that ?

Didn't you complete all job yet?

**Comment by virtualrealitysystems** [comment]
Hello there,

Greetings from Virtual Reality Systems.

Thanks for using AUMFOR.  
Open source version of AUMFOR supports only Windows platform. 

We have premium version available for Linux and MacOS.
If you are interested in purchasing premium version or demo of premium version for AUMFOR,  please email  us on info@virtualrealitysystems.net
Our Sales Team will help you on that. 

Thanks
